# Generated by Django 2.2 on 2021-01-11 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_comments_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.IntegerField(default=0, verbose_name='Yorum Sayısı'),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Beğeni Sayısı'),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Beğeniler',
                'ordering': ['-date'],
            },
        ),
    ]
