# Generated by Django 2.2 on 2021-01-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Adresi')),
                ('msg', models.TextField(verbose_name='Mesaj')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'İletişim',
                'ordering': ['-date'],
            },
        ),
    ]
